from __future__ import annotations

from datetime import date

from .models import Recommendation
from .profile import get_profile
from .recommendation import romance_policy, row_to_movie
from .recommender_v9 import FastRecommendationEngineV9
from .semantic import extract_semantic, feature_vector
from .util import clamp, cosine_sparse, normalize_text


ENGINE_VERSION = "10.0.0"


# Broad-but-honest thematic bridges. These are NOT factual event matches; they are used only
# for the separate "În spiritul zilei" lane after the precision-first factual lanes.
_EVENT_GROUP_OVERRIDES: dict[str, tuple[tuple[str, ...], ...]] = {
    # Passion / Cross / Holy Week
    "exaltation_cross": (("passion_of_christ",), ("cross_veneration",), ("christianity",), ("faith",)),
    "holy_week": (("passion_of_christ",), ("cross_veneration",), ("christianity",), ("faith",)),
    "holy_thursday": (("passion_of_christ",), ("christianity",), ("faith",)),
    "good_friday": (("passion_of_christ",), ("cross_veneration",), ("christianity",), ("faith",)),
    "holy_saturday": (("passion_of_christ",), ("christianity",), ("faith",)),
    "palm_sunday": (("christianity",), ("faith",)),
    "lazarus_saturday": (("christianity",), ("faith",)),

    # Nativity / Easter cycles
    "nativity": (("christmas",), ("christianity",), ("faith",)),
    "nativity_fast": (("monasticism",), ("christianity",), ("faith",)),
    "synaxis_theotokos": (("christmas",), ("christianity",), ("faith",)),
    "easter": (("easter",), ("christianity",), ("faith",)),
    "bright_week": (("easter",), ("christianity",), ("faith",)),
    "ascension": (("christianity",), ("faith",)),
    "pentecost": (("christianity",), ("faith",)),
    "great_lent": (("monasticism",), ("christianity",), ("faith",)),
    "dormition_fast": (("monasticism",), ("christianity",), ("faith",)),
    "apostles_fast": (("monasticism",), ("christianity",), ("faith",)),

    # Specific historical anchors
    "holocaust_day": (("holocaust",),),
    "september_11": (("terrorism",),),
    "ww2_start": (("ww2",),),
    "victory_europe": (("ww2",), ("peace", "history")),
    "armistice": (("ww1",), ("peace", "history")),
    "august_23_1944": (("romania", "ww2"), ("romania", "war")),
    "romanian_revolution": (("romania", "revolution"), ("communism", "revolution")),
    "berlin_wall": (("communism",),),
    "union_principalities": (("romania", "history"), ("romania", "politics")),
    "romania_national": (("romania", "history"),),
    "romanian_independence": (("romania", "history"), ("romania", "war")),
    "army_day_ro": (("romania", "war"),),

    # Civic/cultural/thematic days
    "romanian_culture": (("romania", "biography"), ("art",),),
    "brancusi_day": (("art",), ("romania", "biography")),
    "womens_day": (("women",),),
    "labour_day": (("labour",),),
    "children_day": (("children",),),
    "earth_day": (("nature",),),
    "environment_day": (("nature",),),
    "peace_day": (("peace",), ("reconciliation",)),
    "human_rights": (("human_rights",), ("peace",)),
    "tourism_day": (("travel",),),
    "halloween": (("halloween",), ("folk_horror",)),
}


_RELIGIOUS_KEYS = {
    "christianity", "faith", "saints", "monasticism", "passion_of_christ",
    "cross_veneration", "easter", "christmas",
}
_GENERIC_ONLY = {
    "history", "politics", "death", "dark", "contemplative", "hopeful",
    "spring", "summer", "autumn", "winter", "family",
}


class FastRecommendationEngineV10(FastRecommendationEngineV9):
    """Calendar recommendations that remain useful when exact matches are scarce.

    Factual lanes stay precision-first. When a concrete event is active, generic seasonal
    filler is removed and replaced by a separate thematic lane. Thematic candidates must
    still carry a subject related to the event, and are ranked using the user's own highly
    rated event-relevant films as seeds whenever possible.
    """

    RELATED_LIMIT = 6
    SEED_LIMIT = 24

    def __init__(self, db, calendar=None):
        super().__init__(db, calendar)
        self._last_calendar_rows = []
        self._event_seed_cache: dict[tuple, list[tuple]] = {}

    def _candidate_rows(self, when: date, limit: int = 100000):
        rows = super()._candidate_rows(when, limit)
        if self._calendar_candidate_mode:
            self._last_calendar_rows = list(rows)
        return rows

    @staticmethod
    def _merged_semantic(movie):
        # Re-run extraction so newly-added local patterns immediately help old catalog rows
        # whose semantic_json was generated by an earlier version.
        merged = dict(movie.semantic or {})
        for key, value in extract_semantic(movie).items():
            merged[key] = max(float(merged.get(key, 0.0) or 0.0), float(value or 0.0))
        return merged

    def _event_groups(self, ev) -> tuple[tuple[str, ...], ...]:
        override = _EVENT_GROUP_OVERRIDES.get(ev.key)
        if override:
            return override

        if ev.category in {"ortodox", "perioada_ortodoxa"}:
            specific = [k for k in ev.themes if k in _RELIGIOUS_KEYS]
            groups = [(k,) for k in specific]
            for fallback in ("christianity", "faith"):
                if (fallback,) not in groups:
                    groups.append((fallback,))
            if "saints" in ev.themes and ("saints",) not in groups:
                groups.insert(0, ("saints",))
            return tuple(groups)

        # For other concrete days derive only from non-generic subject tags. Broad words like
        # History/Politics alone are deliberately not allowed to create a thematic relation.
        subject = [
            k for k in ev.themes
            if k not in _GENERIC_ONLY and k not in {"war"}
        ]
        groups = [(k,) for k in subject]
        if "romania" in ev.themes:
            if "history" in ev.themes:
                groups.insert(0, ("romania", "history"))
            if "war" in ev.themes:
                groups.insert(0, ("romania", "war"))
        return tuple(dict.fromkeys(groups))

    def _related_relation(self, movie, when: date):
        sem = self._merged_semantic(movie)
        text = normalize_text(" ".join([
            movie.title or "", movie.original_title or "", movie.overview or "",
            " ".join(movie.keywords or []),
        ]))
        best = (0.0, None, "", "")

        for ev, proximity in self.calendar.relevant_events(when):
            if ev.category == "sezon":
                continue
            groups = self._event_groups(ev)
            group_best = 0.0
            group_label = ""
            for group in groups:
                vals = [float(sem.get(tag, 0.0) or 0.0) for tag in group]
                if not vals or any(v < .35 for v in vals):
                    continue
                raw = min(vals)
                # Multi-tag groups are stronger evidence than one broad thematic tag.
                if len(group) > 1:
                    raw = min(1.0, raw + .16)
                if raw > group_best:
                    group_best = raw
                    group_label = " + ".join(tag.replace("_", " ") for tag in group)

            # Event-specific rule phrases can also support a thematic lane. They do not turn
            # this into a factual claim; that decision remains exclusively in v7/v8.
            try:
                from .recommender_v7 import EVENT_RELEVANCE_RULES
                rule = EVENT_RELEVANCE_RULES.get(ev.key) or {}
            except Exception:
                rule = {}
            phrase_hit = ""
            for term in rule.get("terms", ()):
                nt = normalize_text(str(term))
                if nt and nt in text:
                    phrase_hit = str(term)
                    break
            if phrase_hit:
                group_best = max(group_best, .72)
                if not group_label:
                    group_label = phrase_hit

            if group_best <= 0:
                continue
            strength = clamp(group_best * float(ev.importance) * max(.55, float(proximity)))
            if strength > best[0]:
                best = (
                    strength,
                    ev,
                    group_label,
                    f"Tematic pentru {ev.name}: {group_label}. Nu este prezentat ca legătură factuală directă.",
                )
        return best

    def _rated_event_seeds(self, when: date):
        cache_key = (when.isoformat(), self._state_token())
        cached = self._event_seed_cache.get(cache_key)
        if cached is not None:
            return cached

        with self.db.connect() as con:
            rows = con.execute(
                """SELECT m.*, r.rating AS user_rating
                   FROM ratings r JOIN movies m ON m.id=r.movie_id
                   WHERE r.rating>=7
                   ORDER BY r.rating DESC, COALESCE(m.imdb_rating,0) DESC
                   LIMIT 500"""
            ).fetchall()

        seeds = []
        for row in rows:
            movie = row_to_movie(row)
            strength, ev, label, _reason = self._related_relation(movie, when)
            if strength < .22 or ev is None:
                continue
            movie.semantic = self._merged_semantic(movie)
            seeds.append((movie, int(row["user_rating"]), strength, label, feature_vector(movie)))
        seeds.sort(key=lambda item: (item[1], item[2]), reverse=True)
        seeds = seeds[:self.SEED_LIMIT]
        if len(self._event_seed_cache) > 20:
            self._event_seed_cache.clear()
        self._event_seed_cache[cache_key] = seeds
        return seeds

    def _build_related_recommendations(self, when: date, existing_ids: set[int], count: int):
        rows = list(self._last_calendar_rows or [])
        if not rows:
            return []

        profile = get_profile(self.db)
        context = self._run_context()
        exclude_romance = bool(self.db.get_setting("exclude_romance", True))
        seeds = self._rated_event_seeds(when)

        candidates = []
        for row in rows:
            mid = int(row["id"])
            if mid in existing_ids:
                continue
            movie = row_to_movie(row)
            movie.semantic = self._merged_semantic(movie)
            allowed, _penalty, _why = romance_policy(movie, exclude_romance)
            if not allowed:
                continue

            strength, ev, label, reason = self._related_relation(movie, when)
            if strength < .20 or ev is None:
                continue

            score = self._score_one(movie, when, profile, context, exclude_romance, mode="calendar")
            if score is None:
                continue
            if score.confidence >= .55 and score.predicted_rating < 5.8:
                continue

            sim = 0.0
            seed_title = ""
            seed_rating = 0
            if seeds:
                vec = feature_vector(movie)
                for seed_movie, rating, _seed_strength, _seed_label, seed_vec in seeds:
                    candidate_sim = cosine_sparse(vec, seed_vec)
                    if candidate_sim > sim:
                        sim = candidate_sim
                        seed_title = seed_movie.title
                        seed_rating = rating

            # The event relationship remains the gate; personal taste and similarity to the
            # user's own relevant favourites decide ordering inside that gate.
            value = .46 * strength + .34 * float(score.final) + .20 * float(sim)
            score.calendar_kind = "tematică"
            if seed_title and sim >= .20:
                score.calendar_reason = (
                    reason + f" Se apropie și de «{seed_title}», pe care l-ai notat {seed_rating}/10."
                )
            else:
                score.calendar_reason = reason
            candidates.append((value, strength, sim, Recommendation(movie, score)))

        candidates.sort(
            key=lambda item: (
                item[0], item[1], item[2], item[3].score.predicted_rating,
                item[3].score.confidence,
            ),
            reverse=True,
        )
        picked = [item[3] for item in candidates[:max(1, int(count))]]
        self._assert_no_blocked_leak(picked)
        return picked

    def calendar_day_program(self, when: date | None = None, count_per_section: int = 6) -> dict:
        when = when or date.today()
        result = super().calendar_day_program(when, count_per_section)
        sections = list(result.get("sections") or [])

        concrete = [
            (ev, proximity)
            for ev, proximity in self.calendar.relevant_events(when)
            if ev.category != "sezon" and float(ev.importance) * float(proximity) >= .28
        ]
        if not concrete:
            # Ordinary days can keep v8's honest seasonal/personal fallback.
            return result

        # A concrete feast/commemoration is active: never lead with generic late-summer,
        # beach, winter etc. filler. Those are the cards that made Program calendar useless.
        factual_keys = {"exact", "direct", "spiritual", "historical"}
        factual = [s for s in sections if s.get("key") in factual_keys]
        existing_ids = {
            int(rec.movie.id)
            for section in factual
            for rec in (section.get("recommendations") or [])
        }

        related = self._build_related_recommendations(
            when,
            existing_ids,
            max(3, min(self.RELATED_LIMIT, int(count_per_section or self.RELATED_LIMIT))),
        )
        if related:
            factual.append({
                "key": "related",
                "title": "În spiritul zilei",
                "subtitle": (
                    "Filme nevăzute cu temă real apropiată de reperul zilei, ordonate după gustul tău. "
                    "Nu sunt etichetate fals ca fiind despre evenimentul însuși."
                ),
                "recommendations": related,
            })

        # If there are no factual or thematic matches, return no random seasonal cards. The UI
        # will state honestly that no eligible unseen match was found instead of showing Beach.
        result["sections"] = factual
        result["event_related_count"] = len(related)
        result["specific_event_active"] = True
        return result
